/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.milionerzy;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author tobia
 */
public class NewJFrame extends javax.swing.JFrame {

    int pytanie=0;
    char odpowiedz;
    int wygrana=0;
    int tel=0;
    int pub=0;
    int pol=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\0.png");
        jLabel5.setIcon(icon1);
        ImageIcon icon2 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\publicznosc.png");
        ImageIcon icon3 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\5050.png");
        ImageIcon icon4 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\tel.png");
        jLabel1.setIcon(icon2);
        jLabel2.setIcon(icon3);
        jLabel3.setIcon(icon4);
        ImageIcon icon = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\logo.jpg");
        this.setIconImage(icon.getImage());
        this.setTitle("Milionerzy");
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pyt = new javax.swing.JTextField();
        odpa = new javax.swing.JTextField();
        odpb = new javax.swing.JTextField();
        odpc = new javax.swing.JTextField();
        odpd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        pyt.setEditable(false);
        pyt.setText("Witaj w grze milionerzy! Kliknij przycisk \"dalej\" by zacząć gre");

        odpa.setEditable(false);
        odpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odpaMouseClicked(evt);
            }
        });

        odpb.setEditable(false);
        odpb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odpbMouseClicked(evt);
            }
        });

        odpc.setEditable(false);
        odpc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odpcMouseClicked(evt);
            }
        });
        odpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odpcActionPerformed(evt);
            }
        });

        odpd.setEditable(false);
        odpd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                odpdMouseClicked(evt);
            }
        });

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Milionerzy");

        jButton1.setText("Dalej");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(odpa, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(odpb))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(odpc, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(odpd)))
                    .addComponent(pyt, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(32, 32, 32)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton1)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(pyt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odpa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odpc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(odpd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odpb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Autorzy: Alexander Sznajder, Norbert Nowak, Tobiasz Rompalski");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        jMenu1.setText("File");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("zamknij");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("zagraj jeszcze raz");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        odpa.setEnabled(true);
        odpb.setEnabled(true);
        odpc.setEnabled(true);
        odpd.setEnabled(true);
        odpa.setBackground(Color.white);
        odpb.setBackground(Color.white);
        odpc.setBackground(Color.white);
        odpd.setBackground(Color.white);
        pytanie++;
        pytania(pytanie);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void odpdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odpdMouseClicked
        sprawdz('d');
    }//GEN-LAST:event_odpdMouseClicked

    private void odpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odpcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_odpcActionPerformed

    private void odpcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odpcMouseClicked
        sprawdz('c');
    }//GEN-LAST:event_odpcMouseClicked

    private void odpbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odpbMouseClicked
        sprawdz('b');
    }//GEN-LAST:event_odpbMouseClicked

    private void odpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odpaMouseClicked
        sprawdz('a');
    }//GEN-LAST:event_odpaMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(pytanie>0){
        ImageIcon icon6 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\5050_1.png");
        jLabel2.setIcon(icon6);
        
        if(pol==0){
        
        if(pytanie==1){
        odpa.setEnabled(false);
        odpa.setText("");
        odpc.setEnabled(false);
        odpc.setText("");
        }
         else  if(pytanie==2){
        odpa.setEnabled(false);
        odpa.setText("");
        odpb.setEnabled(false);
        odpb.setText("");
        }
         else  if(pytanie==3){
        odpd.setEnabled(false);
        odpd.setText("");
        odpc.setEnabled(false);
        odpc.setText("");
        }
         else  if(pytanie==4){
        odpa.setEnabled(false);
        odpa.setText("");
        odpd.setEnabled(false);
        odpd.setText("");
        }
         else  if(pytanie==5){
        odpa.setEnabled(false);
        odpa.setText("");
        odpb.setEnabled(false);
        odpb.setText("");
        }
         else  if(pytanie==6){
        odpd.setEnabled(false);
        odpd.setText("");
        odpc.setEnabled(false);
        odpc.setText("");
        }
         else  if(pytanie==7){
        odpa.setEnabled(false);
        odpa.setText("");
        odpc.setEnabled(false);
        odpc.setText("");
        }
         else  if(pytanie==8){
        odpb.setEnabled(false);
        odpb.setText("");
        odpd.setEnabled(false);
        odpd.setText("");
        }
         else  if(pytanie==9){
        odpa.setEnabled(false);
        odpa.setText("");
        odpb.setEnabled(false);
        odpb.setText("");
        }
         else  if(pytanie==10){
        odpb.setEnabled(false);
        odpb.setText("");
        odpd.setEnabled(false);
        odpd.setText("");
        }
         else  if(pytanie==11){
        odpa.setEnabled(false);
        odpa.setText("");
        odpd.setEnabled(false);
        odpd.setText("");
        }
        pol++;
        }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(pytanie>0){
        ImageIcon icon5 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\tel_1.png");
        jLabel3.setIcon(icon5);
        if(tel==0){
        Random rand= new Random();
        int a=rand.nextInt(3)+1;
        char b='A';
        int c=rand.nextInt(3)+1;
         if(c==1){
           b='A';
        }
        else if(c==2){
            b='A';
        }
        else if(c==3){
            b='C';
        }
        else if(c==4){
            b='D';
        }
        if(a==1){
           jLabel7.setText("Wydaje mi się że... "+b);
        }
        else if(a==2){
            jLabel7.setText("Na pewno odpowiedz "+b);
        }
        else if(a==3){
            jLabel7.setText("Nie jestem pewien ale mysle ze to moze byc "+b);
        }
        else if(a==4){
            jLabel7.setText("Zgadywałbym że "+b);
        }
        tel++;
        }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        pyt.setText("");
        odpa.setText("");
        odpb.setText("");
        odpc.setText("");
        odpd.setText("");
        pytanie=0;
        jButton1.setEnabled(true);
        wygrana=0;
        ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\0.png");
        jLabel5.setIcon(icon1);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    public void pytania(int pytanie){
        
        if(pytanie==1){
            jButton1.setEnabled(false);
            pyt.setText("Podstawowym składnikiem szkła jest:");
            odpa.setText("A.arsen");
            odpb.setText("B.ołów");
            odpc.setText("C.potas");
            odpd.setText("D.kwarc");
        }
         else  if(pytanie==2){
             jButton1.setEnabled(false);
            pyt.setText("Do której godziny Kopciuszek mógł zostać na balu?");
            odpa.setText("A.do 21:00");
            odpb.setText("B.do 22:00");
            odpc.setText("C.do 23:00");
            odpd.setText("D.do północy");
        }
         else  if(pytanie==3){
             jButton1.setEnabled(false);
            pyt.setText(".Gdzie uprawia się sport zwany pelotą?");
            odpa.setText("A.w Hiszpanii");
            odpb.setText("B.w Brazylii");
            odpc.setText("C.w Polsce");
            odpd.setText("D.w Anglii");
        }
         else  if(pytanie==4){
             jButton1.setEnabled(false);
            pyt.setText(".Największy półwysep świata to Półwysep:");
            odpa.setText("A.Iberyjski");
            odpb.setText("B.Arabski");
            odpc.setText("C.Krymski");
            odpd.setText("D.Apeniński");
        }
         else  if(pytanie==5){
             jButton1.setEnabled(false);
            pyt.setText("Komiksowym \"dzieckiem\" rysownika Boba Kane'a jest:");
            odpa.setText("A.Superman");
            odpb.setText("B.Spider-man");
            odpc.setText("C.Batman");
            odpd.setText("D.Captain America");
        }
         else  if(pytanie==6){
             jButton1.setEnabled(false);
            pyt.setText("Który z kompozytorów w młodości nazywany był \"królem walca\"?");
            odpa.setText("A.Johann Straus");
            odpb.setText("B.Jan Sebastian Bach");
            odpc.setText("C.Józef Haydn");
            odpd.setText("D.Ryszard Wagner");
        }
         else  if(pytanie==7){
             jButton1.setEnabled(false);
            pyt.setText("Człowiek skazany na wygnanie z ojczyzny to:");
            odpa.setText("A.cudzoziemiec");
            odpb.setText("B.apatryda");
            odpc.setText("C.obywatel");
            odpd.setText("D.banita");
        }
         else  if(pytanie==8){
             jButton1.setEnabled(false);
            pyt.setText(".Który król założył obok Krakowa miasta Kazimierz i Kleparz?");
            odpa.setText("A.Kazimierz III Wielki");
            odpb.setText("B.Kazimierz II Sprawiedliwy");
            odpc.setText("C.Kazimierz I Odnowiciel");
            odpd.setText("D.Władysław Łokietek");
        }
         else  if(pytanie==9){
             jButton1.setEnabled(false);
            pyt.setText("Kategorią prawa jazdy w Polsce nie jest:");
            odpa.setText("A.A");
            odpb.setText("B.B");
            odpc.setText("C.Ć");
            odpd.setText("D.D");
        }
         else  if(pytanie==10){
             jButton1.setEnabled(false);
            pyt.setText("W którym z miast znajdują się korty Flushing Meadows?");
            odpa.setText("A.w Londynie");
            odpb.setText("B.w Paryżu");
            odpc.setText("C.w Nowym Jorku");
            odpd.setText("D.w Wiedniu");
        }
         else  if(pytanie==11){
             jButton1.setEnabled(false);
            pyt.setText("Co jest głównym składnikiem maści ichtiolowej?");
            odpa.setText("A.tlenek cynku");
            odpb.setText("B.szkielet ryb karpiowatych");
            odpc.setText("C.łupki bitumiczne");
            odpd.setText("D.tran");
        }
    }
    public void sprawdz(char odpowiedz){
        
        if(pytanie==1){
         if(odpowiedz=='d'){
             wygrana=1000;
             jButton1.setEnabled(true);
                odpd.setBackground(Color.green);
                odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\1.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='c'){
                    odpc.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='a'){
                    odpa.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                }
            }
        }
         else  if(pytanie==2){
        if(odpowiedz=='d'){
            wygrana=2000;
            jButton1.setEnabled(true);
                odpd.setBackground(Color.green);
                odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\2.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='c'){
                    odpc.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='a'){
                    odpa.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                }
            }
        }
         else  if(pytanie==3){
        if(odpowiedz=='a'){
            wygrana=3000;
            jButton1.setEnabled(true);
                odpa.setBackground(Color.green);
                odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\3.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='c'){
                    odpc.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='d'){
                    odpd.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                }
            }
        }
         else  if(pytanie==4){
         if(odpowiedz=='b'){
             wygrana=6500;
             jButton1.setEnabled(true);
                odpb.setBackground(Color.green);
                odpa.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\4.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='a'){
                    odpa.setBackground(Color.red);
                    odpb.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='c'){
                    odpc.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='d'){
                    odpd.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                }
            }
        }
         else  if(pytanie==5){
          if(odpowiedz=='c'){
              wygrana=12500;
              jButton1.setEnabled(true);
                odpc.setBackground(Color.green);
                odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\5.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='a'){
                    odpa.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='d'){
                    odpd.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                }
            }
        }
         else  if(pytanie==6){
            if(odpowiedz=='a'){
                wygrana=25000;
                jButton1.setEnabled(true);
                odpa.setBackground(Color.green);
                odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\6.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='c'){
                    odpc.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='d'){
                    odpd.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                }
            }
        }
         else  if(pytanie==7){
            if(odpowiedz=='d'){
                wygrana=50000;
                jButton1.setEnabled(true);
                odpd.setBackground(Color.green);
                odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\7.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='c'){
                    odpc.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='a'){
                    odpa.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                }
            }
        }
         else  if(pytanie==8){
            if(odpowiedz=='a'){
                wygrana=125000;
                jButton1.setEnabled(true);
                odpa.setBackground(Color.green);
                odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\8.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='c'){
                    odpc.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='d'){
                    odpd.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                }
            }
        }
         else  if(pytanie==9){
                if(odpowiedz=='c'){
                    wygrana=250000;
                    jButton1.setEnabled(true);
                odpc.setBackground(Color.green);
                odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\9.png");
                jLabel5.setIcon(icon1);
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='a'){
                    odpa.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='d'){
                    odpd.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                }
            }
        }
         else  if(pytanie==10){
           if(odpowiedz=='c'){
               wygrana=500000;
               jButton1.setEnabled(true);
                odpc.setBackground(Color.green);
                odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\10.png");
                jLabel5.setIcon(icon1);
                
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                pyt.setText("Wygrana: "+wygrana);
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='a'){
                    odpa.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='d'){
                    odpd.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                }
            }
        }
         else  if(pytanie==11){
            if(odpowiedz=='c'){
                wygrana=1000000;
                jButton1.setEnabled(true);
                odpc.setBackground(Color.green);
                odpb.setEnabled(false);
                odpa.setEnabled(false);
                odpd.setEnabled(false);
                ImageIcon icon1 = new ImageIcon("C:\\Users\\tobia\\OneDrive\\Dokumenty\\NetBeansProjects\\milionerzy\\src\\main\\java\\img\\11.png");
                jLabel5.setIcon(icon1);
                pyt.setText("Gratulacje wygrałeś milion!");
            }
            else{
                jButton1.setEnabled(false);
                jButton1.setText("Koniec gry");
                if(odpowiedz=='b'){
                    odpb.setBackground(Color.red);
                    odpa.setEnabled(false);
                    odpc.setEnabled(false);
                    odpd.setEnabled(false);
                }
                if(odpowiedz=='a'){
                    odpa.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpd.setEnabled(false);
                }
                if(odpowiedz=='d'){
                    odpd.setBackground(Color.red);
                    odpb.setEnabled(false);
                odpc.setEnabled(false);
                odpa.setEnabled(false);
                }
            }
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField odpa;
    private javax.swing.JTextField odpb;
    private javax.swing.JTextField odpc;
    private javax.swing.JTextField odpd;
    private javax.swing.JTextField pyt;
    // End of variables declaration//GEN-END:variables
}
